# Configures the template for the IDs item, changes to this
# only applies to IDs that are registered after.
# ---
# Available placeholders, applicable everywhere, probably self-explanatory:
# %player's display name%, %player's name%, %player's custom name%, %player's uuid%
# %registrar's display name%, %registrar's name%, %registrar's custom name%
# %registration date%, %expiration date%
# ---
# PlaceholderAPI? Maybe in the future?
id-template:

  # The material of the item. Defaults to PAPER
  # if this value is not present.
  material: PAPER
  display-name: "&e&l[ID] &6%player's display name%"
  lore:
    - ""
    - "&fPlayer's UUID: &a%player's uuid%"
    - "&fRegistrar: &a%registrar's name%"
    - ""
    - "&fGranted on &a%registration date%&f."
    - "&fExpires on &a%expiration date%&f."
